### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by deejaymarkov99** [windytan/darc2json#1]
After cloning locally and installing the dependencies (on ubuntu 16.04) I would get the following errors:

In file included from layer3_4.cc:17:0:
../src/layer3_4.h:121:8: error: ‘unique_ptr’ in namespace ‘std’ does not name a template type
   std::unique_ptr<Json::StreamWriter> writer_;
        ^
layer3_4.cc:42:16: error: ‘chrono’ in namespace ‘std’ does not name a type
     const std::chrono::time_point<std::chrono::system_clock>& timepoint,
                ^
layer3_4.cc:42:34: error: expected unqualified-id before ‘<’ token
     const std::chrono::time_point<std::chrono::system_clock>& timepoint,
                                  ^
layer3_4.cc:42:34: error: expected ‘)’ before ‘<’ token
layer3_4.cc:42:34: error: expected initializer before ‘<’ token
layer3_4.cc:514:1: error: expected ‘}’ at end of input
 }  // namespace darc2json

Fixed this by adding:

`#include <memory>`
`#include <chrono>`

to layer3_4.h

**Comment by windytan** [comment]
Thanks a lot!
